system:
  name: 'app'
  url: 'http://test.example.com'
  addr: 8888
  env: 'develop'
  debug: true

log:
  prefix: '[GO-GIN]'
  log-file: true
  stdout: 'DEBUG'
  file: 'DEBUG'

mysql:
  addr: '127.0.0.1:3306'
  username: 'root'
  password: 'root'
  database: 'test'
  config: 'charset=utf8&parseTime=True&loc=Local'
  max-idle-conns: 10
  max-open-conns: 10
  log-mode: true
  prefix: 't_'

redis:
  addr: '127.0.0.1:6379'
  password: ''
  db: 0
